### ISSUE TITLE
Flightaware piaware error

### ISSUE THREAD

**Issue by orionjb2001** [flightaware/piaware#44] opened 2018-06-09 22:19 UTC
I have a problem installing Flightaware piaware. Running an Odroid XU4, ambrian bionic. Firstly, I am using Joe's ADSB receiver project scripts. First major error, 1090 Flightaware option is not offered as an OS only 1090 mutability. On installing PiAware flightaware, the following error is occuring;

debian/rules build
dh build --with=systemd
dh_update_autotools_config
debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie'
debian/check_versions
piaware version 3.5.3 matches changelog version 3.5.3, good!
cd tcllauncher && autoconf -f && ./configure --with-tcl=/usr/lib/tcl8.6
checking for correct TEA configuration... ok (TEA 3.9)
configure: configuring Tcllauncher 1.5
checking for Tcl configuration... found /usr/lib/tcl8.6/tclConfig.sh
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for existence of /usr/lib/tcl8.6/tclConfig.sh... loading
checking platform... unix
configure: --prefix defaulting to TCL_PREFIX /usr
configure: --exec-prefix defaulting to TCL_EXEC_PREFIX /usr
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking whether make sets $(MAKE)... yes
checking for ranlib... ranlib
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking if the compiler understands -pipe... yes
checking whether byte ordering is bigendian... no
checking for sin... no
checking for main in -lieee... no
checking for main in -linet... no
checking net/errno.h usability... no
checking net/errno.h presence... no
checking for net/errno.h... no
checking for connect... yes
checking for gethostbyname... yes
checking dirent.h... yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking values.h usability... yes
checking values.h presence... yes
checking for values.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking for Tcl public headers... /usr/include/tcl8.6
checking for pthread_mutex_init in -lpthread... yes
checking for building with threads... yes (default)
checking how to build libraries... shared
checking for ranlib... (cached) ranlib
checking if 64bit support is requested... no
checking if 64bit Sparc VIS support is requested... no
checking if compiler supports visibility "hidden"... yes
checking if rpath support is requested... yes
checking system version... Linux-4.9.99-odroidxu4
checking for ar... ar
checking for cast to union support... yes
checking for required early compiler flags... _LARGEFILE64_SOURCE
checking for 64-bit integer type... long long
checking for struct dirent64... yes
checking for struct stat64... yes
checking for open64... yes
checking for lseek64... yes
checking for off64_t... yes
checking for build with symbols... no
checking for tclsh... /usr/bin/tclsh8.6
checking for dtplite... /usr/bin/dtplite
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pkgIndex.tcl
config.status: creating tcllauncher-support.tcl
dh override_dh_auto_configure --with=systemd
make[1]: Leaving directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie'
debian/rules override_dh_auto_build
make[1]: Entering directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie'
dh_auto_build -D tcllauncher
cd tcllauncher && make -j1
make[2]: Entering directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie/tcllauncher'
gcc -DPACKAGE_NAME="Tcllauncher" -DPACKAGE_TARNAME="tcllauncher" -DPACKAGE_VERSION="1.5" -DPACKAGE_STRING="Tcllauncher\ 1.5" -DPACKAGE_BUGREPORT="" -DPACKAGE_URL="" -DBUILD_Tcllauncher=/**/ -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LIMITS_H=1 -DHAVE_SYS_PARAM_H=1 -DUSE_THREAD_ALLOC=1 -D_REENTRANT=1 -D_THREAD_SAFE=1 -DTCL_THREADS=1 -DMODULE_SCOPE=extern\ attribute((visibility("hidden"))) -DHAVE_HIDDEN=1 -DHAVE_CAST_TO_UNION=1 -D_LARGEFILE64_SOURCE=1 -DTCL_WIDE_INT_TYPE=long\ long -DHAVE_STRUCT_DIRENT64=1 -DHAVE_STRUCT_STAT64=1 -DHAVE_OPEN64=1 -DHAVE_LSEEK64=1 -DHAVE_TYPE_OFF64_T=1 -DUSE_TCL_STUBS=1 -I./generic -I"/usr/include/tcl8.6" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -pipe -Wdate-time -D_FORTIFY_SOURCE=2 -c -O2 -fomit-frame-pointer -DNDEBUG -Wall 
-DTCLLAUNCHER_FILE=""/usr/lib/Tcllauncher1.5/tcllauncher.tcl"" unix/tclAppInit.c
gcc -o tcllauncher tclAppInit.o -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -pipe -Wdate-time -D_FORTIFY_SOURCE=2 -O2 -fomit-frame-pointer -DNDEBUG -Wall 
-L/usr/lib/arm-linux-gnueabihf -ltcl8.6 -L/usr/lib/arm-linux-gnueabihf -ltclstub8.6 -lpthread
make[2]: Leaving directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie/tcllauncher'
make -C dump1090 RTLSDR=no BLADERF=no DUMP1090_VERSION="piaware-3.5.3" faup1090
make[2]: Entering directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie/dump1090'
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c faup1090.c -o faup1090.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c anet.c -o anet.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c mode_ac.c -o mode_ac.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c mode_s.c -o mode_s.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c net_io.c -o net_io.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c crc.c -o crc.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c stats.c -o stats.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c cpr.c -o cpr.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c icao_filter.c -o icao_filter.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c track.c -o track.o
cc -Wdate-time -D_FORTIFY_SOURCE=2 -DMODES_DUMP1090_VERSION="piaware-3.5.3" -DMODES_DUMP1090_VARIANT="dump1090-fa" -g -O2 -fdebug-prefix-map=/home/pi/adsb-receiver/build/piaware_builder/package-jessie=. -fstack-protector-strong -Wformat -Werror=format-security -std=c11 -O2 -g -Wall -Werror -W -D_DEFAULT_SOURCE -c util.c -o util.o
cc -g -o faup1090 faup1090.o anet.o mode_ac.o mode_s.o net_io.o crc.o stats.o cpr.o icao_filter.o track.o util.o -Wl,-Bsymbolic-functions -Wl,-z,relro -lpthread -lm -lrt
make[2]: Leaving directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie/dump1090'
pyvenv /home/pi/adsb-receiver/build/piaware_builder/package-jessie/debian/venv --without-pip
WARNING: the pyenv script is deprecated in favour of python3.6 -m venv
cd cx_Freeze-4.3.4 && /home/pi/adsb-receiver/build/piaware_builder/package-jessie/debian/venv/bin/python ./setup.py install
Traceback (most recent call last):
File "./setup.py", line 138, in 
finder = cx_Freeze.ModuleFinder(bootstrap = True)
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 160, in init
self._AddBaseModules()
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 187, in _AddBaseModules
self.IncludeModule("traceback")
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 687, in IncludeModule
namespace = namespace)
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 355, in _ImportModule
deferredImports, namespace = namespace)
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 445, in _InternalImportModule
parentModule, namespace)
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 511, in _LoadModule
self._ScanCode(module.code, module, deferredImports)
File "/home/pi/adsb-receiver/build/piaware_builder/package-jessie/cx_Freeze-4.3.4/cx_Freeze/finder.py", line 597, in _ScanCode
arguments.append(co.co_consts[opArg])
IndexError: tuple index out of range
debian/rules:55: recipe for target 'build_cxfreeze' failed
make[1]: *** [build_cxfreeze] Error 1
make[1]: Leaving directory '/home/pi/adsb-receiver/build/piaware_builder/package-jessie'
debian/rules:83: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

Installing the FlightAware PiAware client package...

dpkg: error: cannot access archive '/home/pi/adsb-receiver/build/piaware_builder/piaware_*.deb': No such file or directory

Checking that the FlightAware PiAware client package was installed properly...

INSTALLATION HALTED!
UNABLE TO INSTALL A REQUIRED PACKAGE.
SETUP HAS BEEN TERMINATED!

The package "piaware" could not be installed.

FlightAware PiAware client setup halted.

**Comment by orionjb2001** [comment] 2018-06-11 09:27
Update 24 hours later, no change same error occuring. :(

**Comment by mutability** [comment] 2018-06-11 09:47
This is a duplicate of https://github.com/flightaware/piaware_builder/issues/10

**Closed by mutability** 2018-06-11 09:47 UTC
